//! Canonicalization of individual tensor product terms.

use crate::repr::{
    Coefficient, Computation, Index, IndexId, RangeId, SymmetryAction, SymmetryGenerator, TensorId,
    TensorRef, Term,
};
use std::cmp::Ordering;
use std::collections::{BTreeMap, BTreeSet};

/// A local validation or symmetry failure during term canonicalization.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CanonError {
    UnknownRange {
        range: RangeId,
    },
    UnknownTensor {
        tensor: TensorId,
    },
    TensorArityMismatch {
        tensor: TensorId,
        expected: usize,
        got: usize,
    },
    InvalidSymmetryArity {
        tensor: TensorId,
        expected: usize,
        got: usize,
    },
    InvalidSymmetryPermutation {
        tensor: TensorId,
        perm: Vec<usize>,
    },
    DuplicateFixedIndex {
        index: IndexId,
    },
    DuplicateSummedIndex {
        index: IndexId,
    },
    FixedAndSummedIndexOverlap {
        index: IndexId,
    },
    UnknownIndex {
        index: IndexId,
    },
    UnusedSummedIndex {
        index: IndexId,
    },
    ExhaustedIndexIds,
}

/// Canonicalize one tensor product term while preserving its fixed indices.
///
/// Fixed index IDs are left unchanged. Summed indices are renamed
/// deterministically, factors are treated as commutative, and each tensor
/// occurrence may use any permutation generated by its declared symmetry.
/// The exhaustive search retains only the smallest candidate found.
///
/// `None` denotes a zero term, including one fixed by a sign-negating
/// symmetry.
pub fn canon_term(
    computation: &Computation,
    fixed_indices: &[Index],
    term: &Term,
) -> Result<Option<Term>, CanonError> {
    let context = validate_term(computation, fixed_indices, term)?;
    if is_zero(&term.coeff) {
        return Ok(None);
    }

    let variants = term
        .factors
        .iter()
        .map(|factor| {
            let tensor = &computation.tensors[&factor.tensor];
            factor_variants(factor, tensor.rank, &tensor.symmetry)
        })
        .collect::<Vec<_>>();

    let mut search = Search::new(&context.fixed_ids, &context.sum_ranges, &variants)?;
    search.run(SymmetryAction::Identity);

    if search.saw_identity && search.saw_negate {
        return Ok(None);
    }

    let coeff = if search.saw_negate {
        -term.coeff.clone()
    } else {
        term.coeff.clone()
    };
    let best = search
        .best
        .expect("the identity symmetry and factor ordering always form a candidate");

    Ok(Some(Term {
        sums: best.sums,
        coeff,
        factors: best.factors,
    }))
}

/// Canonicalize a linear expression while preserving its fixed indices.
///
/// Terms are canonicalized with [`canon_term`], equal term bodies are merged,
/// zero terms are removed, and the result is sorted deterministically.
pub fn canon_expr(
    computation: &Computation,
    fixed_indices: &[Index],
    terms: &[Term],
) -> Result<Vec<Term>, CanonError> {
    let mut canonical = Vec::<Term>::new();

    for term in terms {
        let Some(term) = canon_term(computation, fixed_indices, term)? else {
            continue;
        };

        if let Some(existing) = canonical
            .iter_mut()
            .find(|existing| existing.sums == term.sums && existing.factors == term.factors)
        {
            existing.coeff += term.coeff;
        } else {
            canonical.push(term);
        }
    }

    canonical.retain(|term| !is_zero(&term.coeff));
    canonical.sort_by(|left, right| {
        left.sums
            .cmp(&right.sums)
            .then_with(|| left.factors.cmp(&right.factors))
    });

    Ok(canonical)
}

struct TermContext {
    fixed_ids: BTreeSet<IndexId>,
    sum_ranges: BTreeMap<IndexId, RangeId>,
}

fn validate_term(
    computation: &Computation,
    fixed_indices: &[Index],
    term: &Term,
) -> Result<TermContext, CanonError> {
    let mut fixed_ids = BTreeSet::new();
    for index in fixed_indices {
        validate_range(computation, index.range)?;
        if !fixed_ids.insert(index.id) {
            return Err(CanonError::DuplicateFixedIndex { index: index.id });
        }
    }

    let mut sum_ranges = BTreeMap::new();
    for index in &term.sums {
        validate_range(computation, index.range)?;
        if fixed_ids.contains(&index.id) {
            return Err(CanonError::FixedAndSummedIndexOverlap { index: index.id });
        }
        if sum_ranges.insert(index.id, index.range).is_some() {
            return Err(CanonError::DuplicateSummedIndex { index: index.id });
        }
    }

    let mut used_sums = BTreeSet::new();
    for factor in &term.factors {
        let tensor = computation
            .tensors
            .get(&factor.tensor)
            .ok_or(CanonError::UnknownTensor {
                tensor: factor.tensor,
            })?;
        if factor.indices.len() != tensor.rank {
            return Err(CanonError::TensorArityMismatch {
                tensor: factor.tensor,
                expected: tensor.rank,
                got: factor.indices.len(),
            });
        }
        for generator in &tensor.symmetry {
            validate_generator(factor.tensor, tensor.rank, generator)?;
        }

        for &index in &factor.indices {
            if sum_ranges.contains_key(&index) {
                used_sums.insert(index);
            } else if !fixed_ids.contains(&index) {
                return Err(CanonError::UnknownIndex { index });
            }
        }
    }

    if let Some(&index) = sum_ranges.keys().find(|index| !used_sums.contains(index)) {
        return Err(CanonError::UnusedSummedIndex { index });
    }

    Ok(TermContext {
        fixed_ids,
        sum_ranges,
    })
}

fn validate_range(computation: &Computation, range: RangeId) -> Result<(), CanonError> {
    if computation.ranges.contains(&range) {
        Ok(())
    } else {
        Err(CanonError::UnknownRange { range })
    }
}

fn validate_generator(
    tensor: TensorId,
    rank: usize,
    generator: &SymmetryGenerator,
) -> Result<(), CanonError> {
    if generator.perm.len() != rank {
        return Err(CanonError::InvalidSymmetryArity {
            tensor,
            expected: rank,
            got: generator.perm.len(),
        });
    }

    let mut seen = vec![false; rank];
    for &position in &generator.perm {
        if position >= rank || seen[position] {
            return Err(CanonError::InvalidSymmetryPermutation {
                tensor,
                perm: generator.perm.clone(),
            });
        }
        seen[position] = true;
    }

    Ok(())
}

#[derive(Clone, PartialEq, Eq)]
struct SymmetryElement {
    perm: Vec<usize>,
    action: SymmetryAction,
}

#[derive(Clone, PartialEq, Eq)]
struct FactorVariant {
    factor: TensorRef,
    action: SymmetryAction,
}

fn factor_variants(
    factor: &TensorRef,
    rank: usize,
    generators: &[SymmetryGenerator],
) -> Vec<FactorVariant> {
    let mut group = vec![SymmetryElement {
        perm: (0..rank).collect(),
        action: SymmetryAction::Identity,
    }];
    let mut position = 0;
    while position < group.len() {
        let element = group[position].clone();
        for generator in generators {
            let next = SymmetryElement {
                perm: compose(&element.perm, &generator.perm),
                action: combine(element.action, generator.action),
            };
            if !group.contains(&next) {
                group.push(next);
            }
        }
        position += 1;
    }

    let mut variants = Vec::new();
    for element in group {
        let variant = FactorVariant {
            factor: TensorRef {
                tensor: factor.tensor,
                indices: element
                    .perm
                    .iter()
                    .map(|&position| factor.indices[position])
                    .collect(),
            },
            action: element.action,
        };
        if !variants.contains(&variant) {
            variants.push(variant);
        }
    }
    variants
}

/// Compose two preimage permutations, applying `left` and then `right`.
fn compose(left: &[usize], right: &[usize]) -> Vec<usize> {
    right.iter().map(|&position| left[position]).collect()
}

fn combine(left: SymmetryAction, right: SymmetryAction) -> SymmetryAction {
    match (left, right) {
        (SymmetryAction::Identity, action) | (action, SymmetryAction::Identity) => action,
        (SymmetryAction::Negate, SymmetryAction::Negate) => SymmetryAction::Identity,
    }
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct TermKey {
    sums: Vec<Index>,
    factors: Vec<TensorRef>,
}

struct Search<'a> {
    sum_ranges: &'a BTreeMap<IndexId, RangeId>,
    canonical_sum_ids: Vec<IndexId>,
    variants: &'a [Vec<FactorVariant>],
    used_factors: Vec<bool>,
    ordered_factors: Vec<TensorRef>,
    best: Option<TermKey>,
    saw_identity: bool,
    saw_negate: bool,
}

impl<'a> Search<'a> {
    fn new(
        fixed_ids: &BTreeSet<IndexId>,
        sum_ranges: &'a BTreeMap<IndexId, RangeId>,
        variants: &'a [Vec<FactorVariant>],
    ) -> Result<Self, CanonError> {
        Ok(Self {
            sum_ranges,
            canonical_sum_ids: canonical_sum_ids(fixed_ids, sum_ranges.len())?,
            variants,
            used_factors: vec![false; variants.len()],
            ordered_factors: Vec::with_capacity(variants.len()),
            best: None,
            saw_identity: false,
            saw_negate: false,
        })
    }

    fn run(&mut self, action: SymmetryAction) {
        if self.ordered_factors.len() == self.variants.len() {
            self.consider(action);
            return;
        }

        for factor_position in 0..self.variants.len() {
            if self.used_factors[factor_position] {
                continue;
            }

            self.used_factors[factor_position] = true;
            for variant_position in 0..self.variants[factor_position].len() {
                let variant = self.variants[factor_position][variant_position].clone();
                self.ordered_factors.push(variant.factor);
                self.run(combine(action, variant.action));
                self.ordered_factors.pop();
            }
            self.used_factors[factor_position] = false;
        }
    }

    fn consider(&mut self, action: SymmetryAction) {
        let candidate = self.current_key();
        match self.best.as_ref().map(|best| candidate.cmp(best)) {
            None | Some(Ordering::Less) => {
                self.best = Some(candidate);
                self.saw_identity = action == SymmetryAction::Identity;
                self.saw_negate = action == SymmetryAction::Negate;
            }
            Some(Ordering::Equal) => match action {
                SymmetryAction::Identity => self.saw_identity = true,
                SymmetryAction::Negate => self.saw_negate = true,
            },
            Some(Ordering::Greater) => {}
        }
    }

    fn current_key(&self) -> TermKey {
        let mut sum_ids = BTreeMap::new();
        let mut sums = Vec::with_capacity(self.sum_ranges.len());
        let mut factors = Vec::with_capacity(self.ordered_factors.len());

        for factor in &self.ordered_factors {
            let indices = factor
                .indices
                .iter()
                .map(|index| {
                    let Some(&range) = self.sum_ranges.get(index) else {
                        return *index;
                    };
                    if let Some(&id) = sum_ids.get(index) {
                        return id;
                    }

                    let id = self.canonical_sum_ids[sum_ids.len()];
                    sum_ids.insert(*index, id);
                    sums.push(Index { id, range });
                    id
                })
                .collect();
            factors.push(TensorRef {
                tensor: factor.tensor,
                indices,
            });
        }

        TermKey { sums, factors }
    }
}

fn canonical_sum_ids(
    fixed_ids: &BTreeSet<IndexId>,
    count: usize,
) -> Result<Vec<IndexId>, CanonError> {
    if count == 0 {
        return Ok(Vec::new());
    }

    let mut ids = Vec::with_capacity(count);

    for value in 0..=u32::MAX {
        let id = IndexId(value);
        if !fixed_ids.contains(&id) {
            ids.push(id);
            if ids.len() == count {
                return Ok(ids);
            }
        }
    }

    Err(CanonError::ExhaustedIndexIds)
}

fn is_zero(coeff: &Coefficient) -> bool {
    coeff == &Coefficient::from_integer(0.into())
}
